### ISSUE TITLE
Toolbar + headline section height

### ISSUE THREAD

**Issue by dicodiaz** [ramiaquista/ramiaq-portfolio#6]
https://github.com/ramiaquista/ramiaq-portfolio/blob/1c797a2f237548fd1a794196b66d8250e54bb942/style.css#L12

I think it would be better for UX if your toolbar + headline section was exactly 100vh. I think it would be something like calc(100vh - *toolbar height*)

**Comment by ramiaquista** [comment]
Thank's for the advice Dico!
